title: Personal Blog
description: >- # this means to ignore newlines until "baseurl:"
  El objetivo del contenido es que encuentres videotutoriales sobre 
  videojuegos, programaci√≥n y desarrollo web con JavaScript: 
  HTML5/CSS3, React.js, Node.js, Hybrids y otros.
baseurl: ""
url: https://corteshvictor.dev
google_analytics: G-C33X0C9F2V
twitter_username: corteshvictor
github_username: corteshvictor
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
